name=input("Enter is your name")
print("Hello,", name)
print("Hope you are doing well!!")
e=int(input("Enter the marks you got in English"))
m=int(input("Enter the marks you got in Maths"))
h=int(input("Enter the marks you got in Hindi"))
c=int(input("Enter the marks you got in Computer"))
sst=int(input("Enter the marks you got in Social Science"))
s=int(input("Enter the marks you got in Science"))
T=float((e+m+h+c+sst+s)/6)
print("Your Prcentage is :", T,"%")
if (T>=33):
    print("Congratulations!!",name, "You Are Pass!!")
else: print("You Are Faile!!")